allow-loopback-pinentry
pinentry-program /opt/homebrew/bin/pinentry

# Force reauthentication every 14 days
default-cache-ttl 1209600
max-cache-ttl 1209600
default-cache-ttl-ssh 1209600
max-cache-ttl-ssh 1209600
