#:schema https://raw.githubusercontent.com/joshmedeski/sesh/main/sesh.schema.json

[[wildcard]]
pattern = "~/Downloads"
startup_command = "yazi"

[[wildcard]]
pattern = "/Volumes/kioxia-2TB/Downloads"
startup_command = "yazi"
